@startuml

class GUIAction {
    - action_type: GUIActionType
    - timestamp: int
    - x: int
    - y: int
    - key: str
    - button: str
    - text: str
    + execute(): None
    + to_json(gui_action: GUIAction): str
    + from_json(json_data: str): GUIAction
}
enum GUIActionType {
    CLICK
    DOUBLE_CLICK
    KEY_PRESS
    WRITE
}

GUIAction --> GUIActionType

@enduml